theme = "catppuccin_mocha"

[editor]
cursorline = true
rulers = [120]    
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.indent-guides]
character = "|"
render = true

[editor.statusline]
left = ["mode","spinner","version-control","file-name"]

[editor.lsp]
display-messages = true

[keys.normal]
"A-j" = ["extend_to_line_bounds","delete_selection","paste_after"]
"A-k" = ["extend_to_line_bounds","delete_selection","move_line_up","paste_before"]
