# theme = "catppuccin-mocha"

[editor]
cursorline = true
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.indent-guides]
character = "|"
render = true

[editor.statusline]
left = ["mode","spinner","version-control"]
center = ["file-name"]
right = ["diagnostics","selections", "position", "file-encoding", "file-line-ending", "file-type"]
[editor.lsp]
display-messages = true


[keys.normal]
"C-j" = ["extend_to_line_bounds","delete_selection","paste_after"]
"C-down" = ["extend_to_line_bounds","delete_selection","paste_after"]
"C-k" = ["extend_to_line_bounds","delete_selection","move_line_up","paste_before"]
"C-up" = ["extend_to_line_bounds","delete_selection","move_line_up","paste_before"]
"C-a" = ":toggle lsp.display-inlay-hints"

"C-left" = ":buffer-next"
"C-right" = ":buffer-previous"
